### ISSUE TITLE
npm list error

### ISSUE THREAD

**Issue by deywang** [ChinaModernAppGroup/msda-zookeeper#6]

**Comment by deywang** [comment]
[root@79:Offline:Disconnected] nodejs # pwd
/root/msda-zookeeper/src/nodejs
[root@79:Offline:Disconnected] nodejs # npm list
f5-iappslx-msda-zk@0.0.3 /root/msda-zookeeper/src/nodejs
+-- UNMET DEPENDENCY f5-logger@^1.0.0
+-- UNMET DEPENDENCY node-zookeeper-client@^1.1.1
`-- UNMET DEPENDENCY q@^1.5.1

npm ERR! missing: f5-logger@^1.0.0, required by f5-iappslx-msda-zk@0.0.3
npm ERR! missing: node-zookeeper-client@^1.1.1, required by f5-iappslx-msda-zk@0.0.3
npm ERR! missing: q@^1.5.1, required by f5-iappslx-msda-zk@0.0.3
[root@79:Offline:Disconnected] nodejs #

**Comment by xp2014** [comment]
Please try the latest version, it should be fine.
